runtime: python27
api_version: 1
threadsafe: true

vm: true
resources:
  cpu: .5
  memory_gb: 1.3
manual_scaling:
  instances: 1

handlers:
- url: /.*
  script: app.main.app
  login: admin

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*\.so$
- ^(.*/)?.*\_test.(html|js|py)$
- ^(.*/)?.*~
- ^(.*/)?\..*
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?run_tests.py
- bower_components
- env
- htmlconv
- lib/Crypto
- node_modules
- testing
- ^.*.example

