FROM grow/buildbot-baseimage
MAINTAINER Grow SDK Authors <hello@grow.io>

# Add the webserver to /etc/service so that the process will run and be supervised by runit.
ADD prod/run-app.sh /etc/service/app/run
RUN chmod +x /etc/service/app/run

# Add a cron entry for the sync script.
RUN (crontab -l; echo "* * * * * cd /home/app && /sbin/setuser app /home/app/cron.py 2>&1 | logger -p user.info") | crontab

# Add the application.
ADD app /home/app/
