#!/bin/bash

set -e

VERSION=`date +%Y-%m-%d-%H%M%S`
echo "Building version $VERSION"

docker build -f Dockerfile.baseimage -t grow/buildbot-baseimage:latest .

IMAGE=grow/buildbot-master
docker build -f Dockerfile.master -t $IMAGE:$VERSION .
docker tag -f $IMAGE:$VERSION $IMAGE:latest

IMAGE=grow/buildbot-worker
docker build -f Dockerfile.worker -t $IMAGE:$VERSION .
docker tag -f $IMAGE:$VERSION $IMAGE:latest

echo
echo "Built and tagged with '$VERSION' and 'latest'"
echo "Run the ./prod/push_images script to push these images to Docker Hub."
