#!/bin/bash

VMNAME=buildbot-master

echo "Deploying $VMNAME ..."
gcloud compute instances create \
  $VMNAME \
  --image container-vm \
  --machine-type n1-highcpu-8 \
  --scopes https://www.googleapis.com/auth/gerritcodereview,https://www.googleapis.com/auth/logging.write \
  --zone us-central1-a \
  --boot-disk-type pd-ssd \
  --boot-disk-size 200GB
