#!/bin/bash

VMNAME=buildbot-master

# Make sure the current working dir is the same as the script.
cd "$(dirname "$0")"
CURDIR=$(pwd)

echo 'Updating docker images...'
gcloud compute ssh \
  $VMNAME \
  --zone us-central1-a \
  --command "sudo docker pull grow/baseimage && sudo docker pull grow/buildbot-master && sudo docker pull grow/buildbot-worker"

echo 'Deploying updated metadata...'
gcloud compute instances add-metadata \
  $VMNAME \
  --zone us-central1-a \
  --metadata-from-file \
      google-container-manifest=$CURDIR/containers.yaml,startup-script=$CURDIR/master-startup.sh

echo 'Restarting docker containers...'
gcloud compute ssh \
  $VMNAME \
  --zone us-central1-a \
  --command "sudo docker stop -t 120 $(docker ps -q)"
