#!/bin/bash

VMNAME=buildbot-master
DISKNAME=buildbot-data

echo "Deploying $VMNAME ..."

set -e

# Make sure the current working dir is the same as the script.
cd "$(dirname "$0")"
CURDIR=$(pwd)

gcloud compute disks create \
  $DISKNAME \
  --type pd-ssd \
  --size 200GB \
  --zone us-central1-a

gcloud compute instances create \
  $VMNAME \
  --image container-vm \
  --machine-type n1-standard-8 \
  --scopes https://www.googleapis.com/auth/gerritcodereview,https://www.googleapis.com/auth/logging.write \
  --disk name=$DISKNAME,device-name=$DISKNAME,boot=no,auto-delete=no \
  --zone us-central1-a \
  --boot-disk-size 250GB \
  --metadata-from-file \
      google-container-manifest=$CURDIR/containers.yaml,startup-script=$CURDIR/master-startup.sh

echo 'Done!'
echo
echo 'WARNING: make sure that the disk is mounted the first time the instance is created.'
echo 'SSH into the instance, run "mount -a" and look for /data. If not, reboot and check again.'