#!/bin/bash

set -e

pip --version 2>&1> /dev/null || {
  echo "pip not installed. Installing..."
  sudo easy_install pip
  pip install --upgrade pip
}

virtualenv --version 2>&1> /dev/null || {
  echo "virtualenv not installed. Installing..."
  sudo pip install virtualenv
}

virtualenv env
source env/bin/activate
pip install -r app/requirements.txt
deactivate
