#!/bin/bash

set -e

pip --version 2>&1> /dev/null || {
  echo "pip not installed. Installing..."
  sudo easy_install pip
  pip install --upgrade pip
}

virtualenv --version 2>&1> /dev/null || {
  echo "virtualenv not installed. Installing..."
  sudo pip install virtualenv
}

virtualenv env
source env/bin/activate
# Make sure to update Dockerfile.baseimage if you change these.
pip install --upgrade cffi
pip install --upgrade pygit2
pip install --no-deps git+git://github.com/hulu/restfulgit.git
pip install -r app/requirements.txt
deactivate
